apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matachLabels:
      app: mongodb
  template:
    metadata:
      labels: mongdb
    spec: 
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongo-root-password